<?php
namespace App\Services\Forms;

use App\Services\Employee\EmployeeObject;
class FormChangeDepartmentDashboard
{
	 public static function getFormChangeDepartmentDashboard($get_count_emp,$group_age,$get_count_timestamp,$get_count_timestamp_late,$get_count_timestamp_on_time,$get_count_leave){
	 	$form_box_view ='';
	 	$form_table_view ='';
	 	$form_total_emp ='';
      	$form_gender ='';
      	$form_age ='';

      		$count_emp = $get_count_emp->count();
			$form_table_view .='<div class="col-md-12" id="table_view">';
				$form_table_view .='<div class="box box-warning">';
					$form_table_view .='<div class="box-body no-padding">';
						$form_table_view .='<table class="table table-striped table-hover">';
							$form_table_view .='<tbody>';
								$form_table_view .='<tr>';
									$form_table_view .='<th style="width: 40px; text-align: left;">Task</th>';
									$form_table_view .='<th style="width: 30px;">Amount</th>';
									$form_table_view .='<th style="width: 100px;">Progress</th>';
									$form_table_view .='<th style="width: 40px">Percentage</th>';
								$form_table_view .='</tr>';
								$form_table_view .='<tr>';
									$form_table_view .='<td style="text-align: left;">มาทำงาน /COME FOR WORK</td>';
									$form_table_view .='<td> '.$get_count_timestamp.' คน</td>';
									$form_table_view .='<td>';
										$form_table_view .='<div class="progress progress-xs progress-striped active">';
											$form_table_view .='<div class="progress-bar progress-bar-danger" style="width: '.round(($get_count_timestamp*100)/$count_emp,2)."%".';"></div>';
										$form_table_view .='</div>';
									$form_table_view .='</td>';
									$form_table_view .='<td><span class="badge bg-red">'.round(($get_count_timestamp*100)/$count_emp,2).'%</span></td>';
								$form_table_view .='</tr>';
								$form_table_view .='<tr>';
									$form_table_view .='<td style="text-align: left;">มาสาย /LATE FOR WORK</td>';
									$form_table_view .='<td>'.$get_count_timestamp_late.' คน</td>';
									$form_table_view .='<td>';
										$form_table_view .='<div class="progress progress-xs progress-striped active">';
											$form_table_view .='<div class="progress-bar progress-bar-yellow" style="width: '.round(($get_count_timestamp_late*100)/$count_emp,2)."%".';"></div>';
										$form_table_view .='</div>';
									$form_table_view .='</td>';
									$form_table_view .='<td><span class="badge bg-yellow">'.round(($get_count_timestamp_late*100)/$count_emp,2) .'%</span></td>';
								$form_table_view .='</tr>';
								$form_table_view .='<tr>';
									$form_table_view .='<td style="text-align: left;">มาทันเวลา /COME FOR WORK ON TIME</td>';
									$form_table_view .='<td>'.$get_count_timestamp_on_time .' คน</td>';
									$form_table_view .='<td>';
										$form_table_view .='<div class="progress progress-xs progress-striped active">';
											$form_table_view .='<div class="progress-bar progress-bar-primary" style="width: '.round(($get_count_timestamp_on_time*100)/$count_emp,2)."%".';"></div>';
										$form_table_view .='</div>';
									$form_table_view .='</td>';
									$form_table_view .='<td><span class="badge bg-light-blue">'.round(($get_count_timestamp_on_time*100)/$count_emp,2) .'%</span></td>';
								$form_table_view .='</tr>';
								$form_table_view .='<tr>';
									$form_table_view .='<td style="text-align: left;">ลางาน /LEAVE</td>';
									$form_table_view .='<td>'.$get_count_leave .' คน</td>';
									$form_table_view .='<td>';
										$form_table_view .='<div class="progress progress-xs progress-striped active">';
											$form_table_view .='<div class="progress-bar progress-bar-success" style="width: '.round(($get_count_leave*100)/$count_emp,2)."%".';"></div>';
										$form_table_view .='</div>';
									$form_table_view .='</td>';
									$form_table_view .='<td><span class="badge bg-aqua">'.round(($get_count_leave*100)/$count_emp,2) .'%</span></td>';
								$form_table_view .='</tr>';
							$form_table_view .='</tbody>';
						$form_table_view .='</table>';
					$form_table_view .='</div>';
				$form_table_view .='</div>';
			$form_table_view .='</div>';

			$form_box_view .='<div id="box_view" class="">';
				$form_box_view .='<div class="col-md-3">';
					$form_box_view .='<div class="info-box bg-green">';
						$form_box_view .='<span class="info-box-icon"><i class="glyphicon glyphicon-briefcase"></i></span>';
						$form_box_view .='<div class="info-box-content">';
							$form_box_view .='<span class="info-box-text">มาทำงาน /Come to work</span>';

							$form_box_view .='<span class="info-box-number"> '.$get_count_timestamp .' คน</span>';
							$form_box_view .='<div class="progress">';
								$form_box_view .='<div class="progress-bar" style="width: '.round(($get_count_timestamp*100)/$count_emp,2)."%".';"></div>';
							$form_box_view .='</div>';

							$form_box_view .='<span class="progress-description">';
								$form_box_view .=''.round(($get_count_timestamp*100)/$count_emp,2).'';
								$form_box_view .='% วันนี้ จากพนักงานในแผนก';
							$form_box_view .='</span>';
						$form_box_view .='</div>';
					$form_box_view .='</div>';
				$form_box_view .='</div>';

				$form_box_view .='<div class="col-md-3">';
					$form_box_view .='<div class="info-box bg-red">';
						$form_box_view .='<span class="info-box-icon"><i class="glyphicon glyphicon-time"></i></span>';
						$form_box_view .='<div class="info-box-content">';
							$form_box_view .='<span class="info-box-text">มาสาย</span>';
							$form_box_view .='<span class="info-box-number">'.$get_count_timestamp_late .' คน</span>';
							$form_box_view .='<div class="progress">';
								$form_box_view .='<div class="progress-bar" style="width: '.round(($get_count_timestamp_late*100)/$count_emp,2)."%".';"></div>';
							$form_box_view .='</div>';
							$form_box_view .='<span class="progress-description">';
								$form_box_view .=''.round(($get_count_timestamp_late*100)/$count_emp,2).'';
								$form_box_view .='% วันนี้ จากพนักงานในแผนก';
							$form_box_view .='</span>';
						$form_box_view .='</div>';
					$form_box_view .='</div>';
				$form_box_view .='</div>';

				$form_box_view .='<div class="col-md-3">';
					$form_box_view .='<div class="info-box bg-gray">';
						$form_box_view .='<span class="info-box-icon"><i class="glyphicon glyphicon-time"></i></span>';
						$form_box_view .='<div class="info-box-content">';
							$form_box_view .='<span class="info-box-text">มาทันเวลา</span>';
							$form_box_view .='<span class="info-box-number">'.$get_count_timestamp_on_time .' คน</span>';
							$form_box_view .='<div class="progress">';
								$form_box_view .='<div class="progress-bar" style="width: '.round(($get_count_timestamp_on_time*100)/$count_emp,2)."%".';"></div>';
							$form_box_view .='</div>';
							$form_box_view .='<span class="progress-description">';
								$form_box_view .=''.round(($get_count_timestamp_on_time*100)/$count_emp,2) .'';
								$form_box_view .='% วันนี้ จากพนักงานในแผนก';
							$form_box_view .='</span>';
						$form_box_view .='</div>';
					$form_box_view .='</div>';
				$form_box_view .='</div>';

				$form_box_view .='<div class="col-md-3">';
					$form_box_view .='<div class="info-box bg-yellow">';
						$form_box_view .='<span class="info-box-icon"><i class="glyphicon glyphicon-envelope"></i></span>';
	$form_box_view .='<div class="info-box-content">';
							$form_box_view .='<span class="info-box-text">ลางาน /Leaves</span>';
							$form_box_view .='<span class="info-box-number">'.$get_count_leave .' คน</span>';
							$form_box_view .='<div class="progress">';
								$form_box_view .='<div class="progress-bar" style="width: '.round(($get_count_leave*100)/$count_emp,2)."%".';"></div>';
							$form_box_view .='</div>';
							$form_box_view .='<span class="progress-description">';
								$form_box_view .=''.round(($get_count_leave*100)/$count_emp,2) .'';
								$form_box_view .='% วันนี้ จากพนักงานในแผนก';
							$form_box_view .='</span>';
						$form_box_view .='</div>';
					$form_box_view .='</div>';
				$form_box_view .='</div>';
			$form_box_view .='</div>';

			$form_total_emp ='<div class="box-header with-border">';
			$form_total_emp .='<h3 class="box-title">Total Employees.</h3>';
			$form_total_emp .='</div>';
			$form_total_emp .='<div class="box-body no-padding">';
				$form_total_emp .='<div class="row" style="height: 230px;">';
					$form_total_emp .='<div class="col-md-12">';
						$form_total_emp .='<div style="text-align: center; margin-top: 40px;">';
							$form_total_emp .='<span style="font-size: 100px;">'.$get_count_emp->count().'</span>';
						$form_total_emp .='</div>';
					$form_total_emp .='</div>';
				$form_total_emp .='</div>';
			$form_total_emp .='</div>';

				$form_gender .='<div class="box-header with-border">';
					$form_gender .='<h3 class="box-title">Gender.</h3>';
				$form_gender .='</div>';
				$form_gender .='<div id="container" style="height: 230px;"></div>';
				$form_gender .='<script type="text/javascript">anychart.onDocumentReady(function() {';
					$form_gender .='var chart = anychart.bar();';
					$form_gender .='chart.title("");';
					$form_gender .='chart.data([';
						$form_gender .='{x: "ชาย", value: '.$get_count_emp->where("gender" ,"ชาย")->count() .'},';
						$form_gender .='{x: "หญิง", value: '.$get_count_emp->where("gender" ,"หญิง")->count() .' },';
						$form_gender .=']);';
					$form_gender .='chart.container("container");';
					$form_gender .='chart.labels().fontSize(20);';
					$form_gender .='chart.draw();});';
				$form_gender .='</script>';

				$form_age .='<div class="box-header with-border">';
					$form_age .='<h3 class="box-title">Employees by Age Groups.</h3>';
				$form_age .='</div>';

				$age_min_20	= $group_age->where('age','>=',1)->where('age','<=',20)->count();
				$age_21_30	= $group_age->where('age','>=',21)->where('age','<=',30)->count();
				$age_31_40	= $group_age->where('age','>=',31)->where('age','<=',40)->count();
				$age_41_50	= $group_age->where('age','>=',41)->where('age','<=',50)->count();
				$age_max_50	= $group_age->where('age','>=',51)->count();
				$count_emp = $get_count_emp->count(); 

				$form_age .='<table class="table table-bordered">';
					$form_age .='<thead>';
						$form_age .='<tr>';
							$form_age .='<th>Age</th>';
							$form_age .='<th>Progress</th>';
							$form_age .='<th></th>';
							$form_age .='<th>Employee</th>';
						$form_age .='</tr>';
					$form_age .='</thead>';
					$form_age .='<tbody>';
						$form_age .='<tr>';
							$form_age .='<td><20</td>';
							$form_age .='<td>';
								$form_age .='<div class="progress progress-xs progress-striped active">';
									$form_age .='<div class="progress-bar progress-bar-success" style="width: '.round(($age_min_20*100)/$count_emp,2)."%".'"></div>';
								$form_age .='</div>';
							$form_age .='</td>';
							$form_age .='<td>';
								$form_age .='<span class="badge bg-green">'.round(($age_min_20*100)/$count_emp,2) .' %</span>';
							$form_age .='</td>';
							$form_age .='<td>'.$age_min_20.' คน</td>';
						$form_age .='</tr>';
						$form_age .='<tr>';
							$form_age .='<td>21-30</td>';
							$form_age .='<td>';
								$form_age .='<div class="progress progress-xs progress-striped active">';
									$form_age .='<div class="progress-bar progress-bar-danger" style="width: '.round(($age_21_30*100)/$count_emp,2)."%".'"></div>';
								$form_age .='</div>';
							$form_age .='</td>';
							$form_age .='<td>';
								$form_age .='<span class="badge bg-red">'.round(($age_21_30*100)/$count_emp,2) .' %</span>';
							$form_age .='</td>';
							$form_age .='<td>'.$age_21_30.' คน</td>';
						$form_age .='</tr>';
						$form_age .='<tr>';
							$form_age .='<td>31-40</td>';
							$form_age .='<td>';
								$form_age .='<div class="progress progress-xs progress-striped active">';
									$form_age .='<div class="progress-bar progress-bar-primary" style="width: '.round(($age_31_40*100)/$count_emp,2)."%".';"></div>';
								$form_age .='</div>';
							$form_age .='</td>';
							$form_age .='<td>';
								$form_age .='<span class="badge bg-blue">'.round(($age_31_40*100)/$count_emp,2).' %</span>';
							$form_age .='</td>';
							$form_age .='<td>'.$age_31_40.' คน</td>';
						$form_age .='</tr>';
						$form_age .='<tr>';
							$form_age .='<td>41-50</td>';
							$form_age .='<td>';
								$form_age .='<div class="progress progress-xs progress-striped active">';
									$form_age .='<div class="progress-bar progress-bar-info" style="width: '.round(($age_41_50*100)/$count_emp,2)."%".';"></div>';
								$form_age .='</div>';
							$form_age .='</td>';
							$form_age .='<td>';
								$form_age .='<span class="badge bg-aqua">'.round(($age_41_50*100)/$count_emp,2).' %</span>';
							$form_age .='</td>';
							$form_age .='<td>'.$age_41_50.' คน</td>';
						$form_age .='</tr>';
						$form_age .='<tr>';
							$form_age .='<td>>51</td>';
							$form_age .='<td>';
								$form_age .='<div class="progress progress-xs progress-striped active">';
									$form_age .='<div class="progress-bar progress-bar-warning" style="width: '.round(($age_max_50*100)/$count_emp,2)."%".';"></div>';
								$form_age .='</div>';
							$form_age .='</td>';
							$form_age .='<td>';
								$form_age .='<span class="badge bg-orange">'.round(($age_max_50*100)/$count_emp,2).' %</span>';
							$form_age .='</td>';
							$form_age .='<td>'.$age_max_50.' คน</td>';
						$form_age .='</tr>';
					$form_age .='</tbody>';
				$form_age .='</table>';


        return ['form_total_emp' => $form_total_emp, 'form_gender' => $form_gender, 'form_age' => $form_age,'form_box_view' => $form_box_view,'form_table_view' => $form_table_view];

	 }
}